Tf 01 004 teachworks
UCT-IT/edume pull request #14
Opened 2023-11-14 08:30 UTC by jobayeructit

testimotial added

2023-11-15 05:20 UTC, saminsss requested changes

2023-11-15 05:20 UTC, saminsss commented on src/components/TestimonialCarousel/NextArrow.tsx
> +    ></IconButton>
Does this need ending tag?

2023-11-15 05:20 UTC, saminsss commented on src/components/TestimonialCarousel/NextArrow.tsx
Move this under components/common (need to create folder if doesn't exist)

2023-11-15 05:20 UTC, saminsss commented on src/components/TestimonialCarousel/PrevArrow.tsx
Move this under components/common (need to create folder if doesn't exist)

2023-11-15 05:20 UTC, saminsss commented on src/components/TestimonialCarousel/NextArrow.tsx
This arrow can be used in multiple places

2023-11-15 05:28 UTC, saminsss commented on src/Pages/Home/HomePage.tsx
Is there a reason why everything was moved from `page.tsx` to `Homepage.tsx`?

2023-11-15 05:28 UTC, saminsss commented on src/components/TestimonialCarousel/PrevArrow.tsx
> +    ></IconButton>
Does this need ending tag?

2023-11-15 08:44 UTC, jobayeructit commented on src/Pages/Home/HomePage.tsx
yes. I created a folder called pages . inside this I made HomePage.tsx and rendered all the homePage components there. there will be multiple pages in our website. currently we are  working on homepage. So I thought If I put all the pages inside page folder that would be more structured.so is that  folder structure ok or I should change?

2023-11-16 06:02 UTC, saminsss commented on src/Pages/Home/HomePage.tsx
This is fine

2023-11-16 06:04 UTC, closed without merging