Tf 01 002 navbar
UCT-IT/edume pull request #27
Opened 2023-11-19 11:08 UTC by Rasheduluctit

The navbar was Changed and Updated with tailwind css. 
[Navbar.webm](https://github.com/UCT-IT/edume/assets/149924448/b6af9e05-8d4d-42d4-8798-dc7bf5b8608f)
![Navbar-small](https://github.com/UCT-IT/edume/assets/149924448/078735f8-4596-4f22-a33d-7dce00ccbd9c)
![Navbar-large](https://github.com/UCT-IT/edume/assets/149924448/606ff494-85de-453c-8eb9-48fed135db16)

2023-11-20 05:50 UTC, saminsss requested changes

2023-11-20 05:50 UTC, saminsss commented on src/app/layout.tsx
> +        <Navbar></Navbar>
Self closing tag

2023-11-20 05:50 UTC, saminsss commented on src/components/home/Navbar/DropdownMenu.tsx
> +              key={i}
Shouldn't use index for keys

2023-11-20 05:53 UTC, saminsss commented on src/components/home/Navbar/Navbar.tsx
>                Testimonials
Should be coming in from Locales

2023-11-20 05:53 UTC, saminsss commented
Can you add more padding-top/bottom (4px) for menu dropdowns for the lg screens

2023-11-20 05:57 UTC, saminsss commented
This looks weird. Should show a background once scrolled

<img width="1728" alt="Screenshot 2023-11-19 at 9 54 42 PM" src="https://github.com/UCT-IT/edume/assets/24904840/f59e4061-bbb7-402c-b920-f9e67553f2f9">

2023-11-20 07:31 UTC, Rasheduluctit commented on src/app/layout.tsx
> +        <Navbar></Navbar>
done

2023-11-20 07:31 UTC, Rasheduluctit commented on src/components/home/Navbar/DropdownMenu.tsx
> +              key={i}
Then I am using the menu as the key.

2023-11-20 07:32 UTC, Rasheduluctit commented on src/components/home/Navbar/Navbar.tsx
>                Testimonials
done

2023-11-20 07:34 UTC, Rasheduluctit commented
scroll effect was showing when it scrolled down 200px. Now I have changed it to 20px. I hope Now It will be fine.

2023-11-21 06:35 UTC, saminsss approved these changes

2023-11-21 07:11 UTC, merged