Tf 01 003 features
UCT-IT/edume pull request #28
Opened 2023-11-19 11:08 UTC by jobayeructit

completed feature section.

[features.webm](https://github.com/UCT-IT/edume/assets/149924386/99171e17-9aad-4474-ae31-c6c3ed597ca3)
![features](https://github.com/UCT-IT/edume/assets/149924386/41b99d1b-5cb7-4e5b-a5e5-5f885045dff7)

2023-11-20 05:46 UTC, saminsss requested changes
Please remove this [line](https://github.com/UCT-IT/edume/pull/28/files#diff-b6a23ccee71e80a59cf81ed4fc2502c8804182c73c7539ec7f5445b88e89271aL250)

```
bg: {}
```
from locales then you will not need to put in checks for undefined for strings so
```
strings?.features?.business?.title
```
can just be
```
strings.features.business.title
```

2023-11-20 05:46 UTC, saminsss commented on src/app/page.tsx
> +      <HomePage></HomePage>
Needs to be self closing tag

2023-11-20 05:46 UTC, saminsss commented on src/components/home/Features/Business/Business.tsx
> +        <Image
Self closing tag

2023-11-20 05:46 UTC, saminsss commented on src/components/home/Features/Clients/Clients.tsx
> +        <Image
Self closing

2023-11-20 05:46 UTC, saminsss commented on src/components/home/Features/Clients/Clients.tsx
> +          <CommonButton
Self closing

2023-11-20 05:46 UTC, saminsss commented on src/components/home/Features/Communication/Communication.tsx
> +        <Image
Self closing

2023-11-20 05:46 UTC, saminsss commented on src/components/home/Features/Communication/Communication.tsx
> +          <CommonButton
Self closing

2023-11-20 05:46 UTC, saminsss commented on src/components/home/Features/Feature/Feature.tsx
> +          <CommonButton
Self closing

2023-11-20 05:46 UTC, saminsss commented on src/components/home/Features/PaidSection/PaidSection.tsx
> +        <Image
Self closing

2023-11-20 05:46 UTC, saminsss commented on src/components/home/Features/PaidSection/PaidSection.tsx
> +          <CommonButton
Self closing

2023-11-20 05:51 UTC, saminsss commented on src/components/home/Features/Business/Business.tsx
> +                key={index}
Shouldn't use index for keys

2023-11-20 09:47 UTC, jobayeructit commented
> Please remove this [line](https://github.com/UCT-IT/edume/pull/28/files#diff-b6a23ccee71e80a59cf81ed4fc2502c8804182c73c7539ec7f5445b88e89271aL250)
> 
> ```
> bg: {}
> ```
> 
> from locales then you will not need to put in checks for undefined for strings so
> 
> ```
> strings?.features?.business?.title
> ```
> 
> can just be
> 
> ```
> strings.features.business.title
> ```

I tried using like you in works.tsx file but its showing 'strings.works' is possibly 'undefined'.ts(18048)
if I use optional chaining then I got no error

2023-11-21 06:39 UTC, saminsss approved these changes

2023-11-21 07:22 UTC, merged