done overview page
UCT-IT/edume pull request #35
Opened 2023-11-21 10:31 UTC by jobayeructit

completed overview page

2023-11-21 10:34 UTC, Rasheduluctit requested changes

2023-11-21 10:34 UTC, Rasheduluctit commented on src/app/pages/overview/page.tsx
> +        ></iframe>
Should be Self Closing

2023-11-21 10:36 UTC, Rasheduluctit approved these changes

2023-11-23 05:10 UTC, saminsss approved these changes
Looks good

2023-11-23 05:56 UTC, merged